name: Sync to GitCode

on:
  push:
    branches:
      - main
jobs:
  to_gitlab:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          # 手动配置 Git 并推送
      - name: 配置 Git
        run: |
          git config --global user.name "KingPrimes"
          git config --global user.email ${{ secrets.EMAIL }}
          # 添加目标仓库远程地址（SSH 或 HTTPS）
          git remote add gitlab git@jihulab.com:KingPrimes/DataSource.git
          # 导入 SSH 密钥（若使用 SSH）
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H jihulab.com >> ~/.ssh/known_hosts
          - name: 推送镜像
            run: git push --mirror gitlab

  to_gitcode_com:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: yesolutions/mirror-action@master
        with:
          REMOTE: 'https://gitcode.com/KingPrimes/DataSource.git'
          GIT_USERNAME: KingPrimes
          GIT_PASSWORD: ${{ secrets.GIT_CODE_COM }}
  to_gitee:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: yesolutions/mirror-action@master
        with:
          REMOTE: 'https://gitee.com/KingPrime/DataSource.git'
          GIT_USERNAME: KingPrime
          GIT_PASSWORD: ${{ secrets.GIT_EE_COM }}