name: Sync to GitCode

on:
  push:
    branches:
      - main  # 或者你想要监听的分支
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'info'
        type: choice
        options:
          - debug
          - info
          - warning
          - error

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.TOGITCODE }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan gitcode.com >> ~/.ssh/known_hosts

      - name: Sync to GitCode
        run: |
          git remote add gitcode git@gitcode.com:KingPrimes/DataSource.git
          git push -u gitcode main:main