name: Sync to GitCode

on:
  push:
    branches:
      - main
jobs:
  to_gitlab:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: wearerequired/git-mirror-action@v1
        env:
          # SSH 密钥（用于 SSH 协议）或 PAT（用于 HTTPS 协议）
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        with:
          # 目标仓库地址（支持 SSH 或 HTTPS）
          source-repo: "git@github.com:KingPrimes/DataSource.git"  # 当前仓库地址
          destination-repo: "git@jihulab.com:KingPrimes/DataSource.git"  # GitLab 目标地址

  to_gitcode_com:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: yesolutions/mirror-action@master
        with:
          REMOTE: 'https://gitcode.com/KingPrimes/DataSource.git'
          GIT_USERNAME: KingPrimes
          GIT_PASSWORD: ${{ secrets.GIT_CODE_COM }}

  to_gitee:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: yesolutions/mirror-action@master
        with:
          REMOTE: 'https://gitee.com/KingPrime/DataSource.git'
          GIT_USERNAME: KingPrime
          GIT_PASSWORD: ${{ secrets.GIT_EE_COM }}